/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AccessResult = IDL.Variant({
  'ok' : IDL.Null,
  'AlreadyApproved' : IDL.Null,
  'AlreadyPending' : IDL.Null,
  'NotFound' : IDL.Null,
  'NotAuthorized' : IDL.Null,
  'Requested' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const Branch = IDL.Variant({ 'Puyo' : IDL.Null, 'El_Topo' : IDL.Null });
export const StockAdjustmentReason = IDL.Variant({
  'Loss' : IDL.Null,
  'Sale' : IDL.Null,
  'Return' : IDL.Null,
  'ServiceUse' : IDL.Null,
  'Correction' : IDL.Null,
  'Purchase' : IDL.Null,
});
export const Role = IDL.Variant({
  'Technician' : IDL.Null,
  'Admin' : IDL.Null,
  'Vendor' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentId = IDL.Nat;
export const DocumentStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Draft' : IDL.Null,
  'Converted' : IDL.Null,
  'Cancelled' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const CustomerId = IDL.Nat;
export const SalesItem = IDL.Record({
  'partNumber' : IDL.Text,
  'name' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'subtotal' : IDL.Float64,
});
export const DocumentType = IDL.Variant({
  'Invoice' : IDL.Null,
  'Proforma' : IDL.Null,
});
export const SalesDocument = IDL.Record({
  'id' : DocumentId,
  'status' : DocumentStatus,
  'convertedToInvoiceId' : IDL.Opt(DocumentId),
  'total' : IDL.Float64,
  'taxPercent' : IDL.Float64,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'customerId' : CustomerId,
  'items' : IDL.Vec(SalesItem),
  'taxAmount' : IDL.Float64,
  'docType' : DocumentType,
  'subtotal' : IDL.Float64,
  'documentNumber' : IDL.Text,
});
export const CustomerInput = IDL.Record({
  'taxId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'taxId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const SalesItemInput = IDL.Record({
  'partNumber' : IDL.Text,
  'name' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const SalesDocumentInput = IDL.Record({
  'taxPercent' : IDL.Float64,
  'customerId' : CustomerId,
  'items' : IDL.Vec(SalesItemInput),
  'docType' : DocumentType,
});
export const ProductInput = IDL.Record({
  'partNumber' : IDL.Text,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'minStockAlert' : IDL.Nat,
  'description' : IDL.Text,
  'supplierPartNumber' : IDL.Text,
  'marginPercent' : IDL.Float64,
  'costPrice' : IDL.Float64,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'partNumber' : IDL.Text,
  'supplierName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'minStockAlert' : IDL.Nat,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'supplierPartNumber' : IDL.Text,
  'marginPercent' : IDL.Float64,
  'costPrice' : IDL.Float64,
});
export const ServiceInput = IDL.Record({
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const ServiceId = IDL.Nat;
export const Service = IDL.Record({
  'id' : ServiceId,
  'code' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'branch' : Branch,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
});
export const SalesDocumentView = IDL.Record({
  'id' : DocumentId,
  'customerName' : IDL.Text,
  'status' : DocumentStatus,
  'convertedToInvoiceId' : IDL.Opt(DocumentId),
  'total' : IDL.Float64,
  'taxPercent' : IDL.Float64,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'customerId' : CustomerId,
  'items' : IDL.Vec(SalesItem),
  'taxAmount' : IDL.Float64,
  'docType' : DocumentType,
  'subtotal' : IDL.Float64,
  'documentNumber' : IDL.Text,
});
export const LowStockItem = IDL.Record({
  'branch' : Branch,
  'partNumber' : IDL.Text,
  'name' : IDL.Text,
  'minStockAlert' : IDL.Nat,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const AccessStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
});
export const ApprovedUser = IDL.Record({
  'status' : AccessStatus,
  'principal' : UserId,
  'branch' : Branch,
  'approvedAt' : Timestamp,
  'name' : IDL.Text,
  'role' : Role,
});
export const DocumentFilter = IDL.Record({
  'status' : IDL.Opt(DocumentStatus),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
  'customerId' : IDL.Opt(CustomerId),
  'docType' : IDL.Opt(DocumentType),
});
export const InventoryLocation = IDL.Record({
  'branch' : Branch,
  'productId' : ProductId,
  'updatedAt' : Timestamp,
  'quantity' : IDL.Nat,
  'locationLabel' : IDL.Text,
});
export const PendingUser = IDL.Record({
  'principal' : UserId,
  'requestedAt' : Timestamp,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'activateUser' : IDL.Func([IDL.Principal], [AccessResult], []),
  'addStock' : IDL.Func(
      [ProductId, Branch, IDL.Text, IDL.Nat, StockAdjustmentReason, IDL.Text],
      [],
      [],
    ),
  'approveUser' : IDL.Func(
      [IDL.Principal, IDL.Text, Role, Branch],
      [AccessResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
  'confirmDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
  'convertProformaToInvoice' : IDL.Func(
      [DocumentId],
      [IDL.Opt(SalesDocument)],
      [],
    ),
  'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
  'createInvoice' : IDL.Func([SalesDocumentInput], [SalesDocument], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'createProforma' : IDL.Func([SalesDocumentInput], [SalesDocument], []),
  'createService' : IDL.Func([ServiceInput], [Service], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [AccessResult], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
  'getDocument' : IDL.Func(
      [DocumentId],
      [IDL.Opt(SalesDocumentView)],
      ['query'],
    ),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(LowStockItem)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isInitialized' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listApprovedUsers' : IDL.Func([], [IDL.Vec(ApprovedUser)], ['query']),
  'listCustomers' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Customer)],
      ['query'],
    ),
  'listDocuments' : IDL.Func(
      [DocumentFilter],
      [IDL.Vec(SalesDocumentView)],
      ['query'],
    ),
  'listLocationsByBranch' : IDL.Func(
      [Branch],
      [IDL.Vec(InventoryLocation)],
      ['query'],
    ),
  'listLocationsByProduct' : IDL.Func(
      [ProductId],
      [IDL.Vec(InventoryLocation)],
      ['query'],
    ),
  'listPendingUsers' : IDL.Func([], [IDL.Vec(PendingUser)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'rejectUser' : IDL.Func([IDL.Principal], [AccessResult], []),
  'removeStock' : IDL.Func(
      [ProductId, Branch, IDL.Nat, StockAdjustmentReason, IDL.Text],
      [],
      [],
    ),
  'requestAccess' : IDL.Func([], [AccessResult], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'setUserActive' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, Role], [], []),
  'updateCustomer' : IDL.Func(
      [CustomerId, CustomerInput],
      [IDL.Opt(Customer)],
      [],
    ),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AccessResult = IDL.Variant({
    'ok' : IDL.Null,
    'AlreadyApproved' : IDL.Null,
    'AlreadyPending' : IDL.Null,
    'NotFound' : IDL.Null,
    'NotAuthorized' : IDL.Null,
    'Requested' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const Branch = IDL.Variant({ 'Puyo' : IDL.Null, 'El_Topo' : IDL.Null });
  const StockAdjustmentReason = IDL.Variant({
    'Loss' : IDL.Null,
    'Sale' : IDL.Null,
    'Return' : IDL.Null,
    'ServiceUse' : IDL.Null,
    'Correction' : IDL.Null,
    'Purchase' : IDL.Null,
  });
  const Role = IDL.Variant({
    'Technician' : IDL.Null,
    'Admin' : IDL.Null,
    'Vendor' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentId = IDL.Nat;
  const DocumentStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Draft' : IDL.Null,
    'Converted' : IDL.Null,
    'Cancelled' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const CustomerId = IDL.Nat;
  const SalesItem = IDL.Record({
    'partNumber' : IDL.Text,
    'name' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'subtotal' : IDL.Float64,
  });
  const DocumentType = IDL.Variant({
    'Invoice' : IDL.Null,
    'Proforma' : IDL.Null,
  });
  const SalesDocument = IDL.Record({
    'id' : DocumentId,
    'status' : DocumentStatus,
    'convertedToInvoiceId' : IDL.Opt(DocumentId),
    'total' : IDL.Float64,
    'taxPercent' : IDL.Float64,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'customerId' : CustomerId,
    'items' : IDL.Vec(SalesItem),
    'taxAmount' : IDL.Float64,
    'docType' : DocumentType,
    'subtotal' : IDL.Float64,
    'documentNumber' : IDL.Text,
  });
  const CustomerInput = IDL.Record({
    'taxId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'taxId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const SalesItemInput = IDL.Record({
    'partNumber' : IDL.Text,
    'name' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const SalesDocumentInput = IDL.Record({
    'taxPercent' : IDL.Float64,
    'customerId' : CustomerId,
    'items' : IDL.Vec(SalesItemInput),
    'docType' : DocumentType,
  });
  const ProductInput = IDL.Record({
    'partNumber' : IDL.Text,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'minStockAlert' : IDL.Nat,
    'description' : IDL.Text,
    'supplierPartNumber' : IDL.Text,
    'marginPercent' : IDL.Float64,
    'costPrice' : IDL.Float64,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'partNumber' : IDL.Text,
    'supplierName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'minStockAlert' : IDL.Nat,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'supplierPartNumber' : IDL.Text,
    'marginPercent' : IDL.Float64,
    'costPrice' : IDL.Float64,
  });
  const ServiceInput = IDL.Record({
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ServiceId = IDL.Nat;
  const Service = IDL.Record({
    'id' : ServiceId,
    'code' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'branch' : Branch,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
  });
  const SalesDocumentView = IDL.Record({
    'id' : DocumentId,
    'customerName' : IDL.Text,
    'status' : DocumentStatus,
    'convertedToInvoiceId' : IDL.Opt(DocumentId),
    'total' : IDL.Float64,
    'taxPercent' : IDL.Float64,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'customerId' : CustomerId,
    'items' : IDL.Vec(SalesItem),
    'taxAmount' : IDL.Float64,
    'docType' : DocumentType,
    'subtotal' : IDL.Float64,
    'documentNumber' : IDL.Text,
  });
  const LowStockItem = IDL.Record({
    'branch' : Branch,
    'partNumber' : IDL.Text,
    'name' : IDL.Text,
    'minStockAlert' : IDL.Nat,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const AccessStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
  });
  const ApprovedUser = IDL.Record({
    'status' : AccessStatus,
    'principal' : UserId,
    'branch' : Branch,
    'approvedAt' : Timestamp,
    'name' : IDL.Text,
    'role' : Role,
  });
  const DocumentFilter = IDL.Record({
    'status' : IDL.Opt(DocumentStatus),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
    'customerId' : IDL.Opt(CustomerId),
    'docType' : IDL.Opt(DocumentType),
  });
  const InventoryLocation = IDL.Record({
    'branch' : Branch,
    'productId' : ProductId,
    'updatedAt' : Timestamp,
    'quantity' : IDL.Nat,
    'locationLabel' : IDL.Text,
  });
  const PendingUser = IDL.Record({
    'principal' : UserId,
    'requestedAt' : Timestamp,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'activateUser' : IDL.Func([IDL.Principal], [AccessResult], []),
    'addStock' : IDL.Func(
        [ProductId, Branch, IDL.Text, IDL.Nat, StockAdjustmentReason, IDL.Text],
        [],
        [],
      ),
    'approveUser' : IDL.Func(
        [IDL.Principal, IDL.Text, Role, Branch],
        [AccessResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
    'confirmDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
    'convertProformaToInvoice' : IDL.Func(
        [DocumentId],
        [IDL.Opt(SalesDocument)],
        [],
      ),
    'createCustomer' : IDL.Func([CustomerInput], [Customer], []),
    'createInvoice' : IDL.Func([SalesDocumentInput], [SalesDocument], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'createProforma' : IDL.Func([SalesDocumentInput], [SalesDocument], []),
    'createService' : IDL.Func([ServiceInput], [Service], []),
    'deactivateUser' : IDL.Func([IDL.Principal], [AccessResult], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([CustomerId], [IDL.Opt(Customer)], ['query']),
    'getDocument' : IDL.Func(
        [DocumentId],
        [IDL.Opt(SalesDocumentView)],
        ['query'],
      ),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(LowStockItem)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getService' : IDL.Func([ServiceId], [IDL.Opt(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isInitialized' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listApprovedUsers' : IDL.Func([], [IDL.Vec(ApprovedUser)], ['query']),
    'listCustomers' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Customer)],
        ['query'],
      ),
    'listDocuments' : IDL.Func(
        [DocumentFilter],
        [IDL.Vec(SalesDocumentView)],
        ['query'],
      ),
    'listLocationsByBranch' : IDL.Func(
        [Branch],
        [IDL.Vec(InventoryLocation)],
        ['query'],
      ),
    'listLocationsByProduct' : IDL.Func(
        [ProductId],
        [IDL.Vec(InventoryLocation)],
        ['query'],
      ),
    'listPendingUsers' : IDL.Func([], [IDL.Vec(PendingUser)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'rejectUser' : IDL.Func([IDL.Principal], [AccessResult], []),
    'removeStock' : IDL.Func(
        [ProductId, Branch, IDL.Nat, StockAdjustmentReason, IDL.Text],
        [],
        [],
      ),
    'requestAccess' : IDL.Func([], [AccessResult], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'searchServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
    'setUserActive' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, Role], [], []),
    'updateCustomer' : IDL.Func(
        [CustomerId, CustomerInput],
        [IDL.Opt(Customer)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };