/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Branch = { 'Puyo' : null } |
  { 'El_Topo' : null };
export interface Customer {
  'id' : CustomerId,
  'taxId' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type CustomerId = bigint;
export interface CustomerInput {
  'taxId' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export interface DocumentFilter {
  'status' : [] | [DocumentStatus],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
  'customerId' : [] | [CustomerId],
  'docType' : [] | [DocumentType],
}
export type DocumentId = bigint;
export type DocumentStatus = { 'Confirmed' : null } |
  { 'Draft' : null } |
  { 'Converted' : null } |
  { 'Cancelled' : null };
export type DocumentType = { 'Invoice' : null } |
  { 'Proforma' : null };
export interface InventoryLocation {
  'branch' : Branch,
  'productId' : ProductId,
  'updatedAt' : Timestamp,
  'quantity' : bigint,
  'locationLabel' : string,
}
export interface LowStockItem {
  'branch' : Branch,
  'partNumber' : string,
  'name' : string,
  'minStockAlert' : bigint,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Product {
  'id' : ProductId,
  'partNumber' : string,
  'supplierName' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'minStockAlert' : bigint,
  'description' : string,
  'updatedAt' : Timestamp,
  'supplierPartNumber' : string,
  'marginPercent' : number,
  'costPrice' : number,
}
export type ProductId = bigint;
export interface ProductInput {
  'partNumber' : string,
  'supplierName' : string,
  'name' : string,
  'minStockAlert' : bigint,
  'description' : string,
  'supplierPartNumber' : string,
  'marginPercent' : number,
  'costPrice' : number,
}
export type Role = { 'Technician' : null } |
  { 'Admin' : null } |
  { 'Vendor' : null };
export interface SalesDocument {
  'id' : DocumentId,
  'status' : DocumentStatus,
  'convertedToInvoiceId' : [] | [DocumentId],
  'total' : number,
  'taxPercent' : number,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'customerId' : CustomerId,
  'items' : Array<SalesItem>,
  'taxAmount' : number,
  'docType' : DocumentType,
  'subtotal' : number,
  'documentNumber' : string,
}
export interface SalesDocumentInput {
  'taxPercent' : number,
  'customerId' : CustomerId,
  'items' : Array<SalesItemInput>,
  'docType' : DocumentType,
}
export interface SalesDocumentView {
  'id' : DocumentId,
  'customerName' : string,
  'status' : DocumentStatus,
  'convertedToInvoiceId' : [] | [DocumentId],
  'total' : number,
  'taxPercent' : number,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'customerId' : CustomerId,
  'items' : Array<SalesItem>,
  'taxAmount' : number,
  'docType' : DocumentType,
  'subtotal' : number,
  'documentNumber' : string,
}
export interface SalesItem {
  'partNumber' : string,
  'name' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'unitPrice' : number,
  'subtotal' : number,
}
export interface SalesItemInput {
  'partNumber' : string,
  'name' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'unitPrice' : number,
}
export interface Service {
  'id' : ServiceId,
  'code' : string,
  'description' : string,
  'price' : number,
}
export type ServiceId = bigint;
export interface ServiceInput { 'description' : string, 'price' : number }
export type StockAdjustmentReason = { 'Loss' : null } |
  { 'Sale' : null } |
  { 'Return' : null } |
  { 'ServiceUse' : null } |
  { 'Correction' : null } |
  { 'Purchase' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'branch' : Branch,
  'active' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addStock' : ActorMethod<
    [ProductId, Branch, string, bigint, StockAdjustmentReason, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelDocument' : ActorMethod<[DocumentId], boolean>,
  'confirmDocument' : ActorMethod<[DocumentId], boolean>,
  'convertProformaToInvoice' : ActorMethod<[DocumentId], [] | [SalesDocument]>,
  'createCustomer' : ActorMethod<[CustomerInput], Customer>,
  'createInvoice' : ActorMethod<[SalesDocumentInput], SalesDocument>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'createProforma' : ActorMethod<[SalesDocumentInput], SalesDocument>,
  'createService' : ActorMethod<[ServiceInput], Service>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[CustomerId], [] | [Customer]>,
  'getDocument' : ActorMethod<[DocumentId], [] | [SalesDocumentView]>,
  'getLowStockItems' : ActorMethod<[], Array<LowStockItem>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getService' : ActorMethod<[ServiceId], [] | [Service]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'listCustomers' : ActorMethod<[[] | [string]], Array<Customer>>,
  'listDocuments' : ActorMethod<[DocumentFilter], Array<SalesDocumentView>>,
  'listLocationsByBranch' : ActorMethod<[Branch], Array<InventoryLocation>>,
  'listLocationsByProduct' : ActorMethod<[ProductId], Array<InventoryLocation>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'removeStock' : ActorMethod<
    [ProductId, Branch, bigint, StockAdjustmentReason, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'searchServices' : ActorMethod<[string], Array<Service>>,
  'setUserActive' : ActorMethod<[Principal, boolean], undefined>,
  'setUserRole' : ActorMethod<[Principal, Role], undefined>,
  'updateCustomer' : ActorMethod<[CustomerId, CustomerInput], [] | [Customer]>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];