/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface SalesDocumentView {
    id: DocumentId;
    customerName: string;
    status: DocumentStatus;
    convertedToInvoiceId?: DocumentId;
    total: number;
    taxPercent: number;
    createdAt: Timestamp;
    createdBy: UserId;
    customerId: CustomerId;
    items: Array<SalesItem>;
    taxAmount: number;
    docType: DocumentType;
    subtotal: number;
    documentNumber: string;
}
export interface DocumentFilter {
    status?: DocumentStatus;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    customerId?: CustomerId;
    docType?: DocumentType;
}
export interface PendingUser {
    principal: UserId;
    requestedAt: Timestamp;
}
export interface CustomerInput {
    taxId?: string;
    name: string;
    email?: string;
    phone?: string;
}
export interface ServiceInput {
    description: string;
    price: number;
}
export interface ApprovedUser {
    status: AccessStatus;
    principal: UserId;
    branch: Branch;
    approvedAt: Timestamp;
    name: string;
    role: Role;
}
export interface InventoryLocation {
    branch: Branch;
    productId: ProductId;
    updatedAt: Timestamp;
    quantity: bigint;
    locationLabel: string;
}
export type DocumentId = bigint;
export interface LowStockItem {
    branch: Branch;
    partNumber: string;
    name: string;
    minStockAlert: bigint;
    productId: ProductId;
    quantity: bigint;
}
export interface SalesDocument {
    id: DocumentId;
    status: DocumentStatus;
    convertedToInvoiceId?: DocumentId;
    total: number;
    taxPercent: number;
    createdAt: Timestamp;
    createdBy: UserId;
    customerId: CustomerId;
    items: Array<SalesItem>;
    taxAmount: number;
    docType: DocumentType;
    subtotal: number;
    documentNumber: string;
}
export interface SalesItem {
    partNumber: string;
    name: string;
    productId: ProductId;
    quantity: bigint;
    unitPrice: number;
    subtotal: number;
}
export interface SalesDocumentInput {
    taxPercent: number;
    customerId: CustomerId;
    items: Array<SalesItemInput>;
    docType: DocumentType;
}
export type ServiceId = bigint;
export interface SalesItemInput {
    partNumber: string;
    name: string;
    productId: ProductId;
    quantity: bigint;
    unitPrice: number;
}
export interface ProductInput {
    partNumber: string;
    supplierName: string;
    name: string;
    minStockAlert: bigint;
    description: string;
    supplierPartNumber: string;
    marginPercent: number;
    costPrice: number;
}
export interface Service {
    id: ServiceId;
    code: string;
    description: string;
    price: number;
}
export interface Customer {
    id: CustomerId;
    taxId?: string;
    name: string;
    email?: string;
    phone?: string;
}
export type UserId = Principal;
export type CustomerId = bigint;
export type ProductId = bigint;
export interface Product {
    id: ProductId;
    partNumber: string;
    supplierName: string;
    name: string;
    createdAt: Timestamp;
    minStockAlert: bigint;
    description: string;
    updatedAt: Timestamp;
    supplierPartNumber: string;
    marginPercent: number;
    costPrice: number;
}
export interface UserProfile {
    principal: UserId;
    branch: Branch;
    active: boolean;
    name: string;
    createdAt: Timestamp;
    role: Role;
}
export enum AccessResult {
    ok = "ok",
    AlreadyApproved = "AlreadyApproved",
    AlreadyPending = "AlreadyPending",
    NotFound = "NotFound",
    NotAuthorized = "NotAuthorized",
    Requested = "Requested"
}
export enum AccessStatus {
    Inactive = "Inactive",
    Active = "Active"
}
export enum Branch {
    Puyo = "Puyo",
    El_Topo = "El_Topo"
}
export enum DocumentStatus {
    Confirmed = "Confirmed",
    Draft = "Draft",
    Converted = "Converted",
    Cancelled = "Cancelled"
}
export enum DocumentType {
    Invoice = "Invoice",
    Proforma = "Proforma"
}
export enum Role {
    Technician = "Technician",
    Admin = "Admin",
    Vendor = "Vendor"
}
export enum StockAdjustmentReason {
    Loss = "Loss",
    Sale = "Sale",
    Return = "Return",
    ServiceUse = "ServiceUse",
    Correction = "Correction",
    Purchase = "Purchase"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    activateUser(target: Principal): Promise<AccessResult>;
    addStock(productId: ProductId, branch: Branch, locationLabel: string, quantity: bigint, reason: StockAdjustmentReason, note: string): Promise<void>;
    approveUser(target: Principal, name: string, role: Role, branch: Branch): Promise<AccessResult>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelDocument(id: DocumentId): Promise<boolean>;
    confirmDocument(id: DocumentId): Promise<boolean>;
    convertProformaToInvoice(proformaId: DocumentId): Promise<SalesDocument | null>;
    createCustomer(input: CustomerInput): Promise<Customer>;
    createInvoice(input: SalesDocumentInput): Promise<SalesDocument>;
    createProduct(input: ProductInput): Promise<Product>;
    createProforma(input: SalesDocumentInput): Promise<SalesDocument>;
    createService(input: ServiceInput): Promise<Service>;
    deactivateUser(target: Principal): Promise<AccessResult>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: CustomerId): Promise<Customer | null>;
    getDocument(id: DocumentId): Promise<SalesDocumentView | null>;
    getLowStockItems(): Promise<Array<LowStockItem>>;
    getProduct(id: ProductId): Promise<Product | null>;
    getService(id: ServiceId): Promise<Service | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isInitialized(): Promise<boolean>;
    listAllUsers(): Promise<Array<UserProfile>>;
    listApprovedUsers(): Promise<Array<ApprovedUser>>;
    listCustomers(nameFilter: string | null): Promise<Array<Customer>>;
    listDocuments(filter: DocumentFilter): Promise<Array<SalesDocumentView>>;
    listLocationsByBranch(branch: Branch): Promise<Array<InventoryLocation>>;
    listLocationsByProduct(productId: ProductId): Promise<Array<InventoryLocation>>;
    listPendingUsers(): Promise<Array<PendingUser>>;
    listProducts(): Promise<Array<Product>>;
    listServices(): Promise<Array<Service>>;
    rejectUser(target: Principal): Promise<AccessResult>;
    removeStock(productId: ProductId, branch: Branch, quantity: bigint, reason: StockAdjustmentReason, note: string): Promise<void>;
    requestAccess(): Promise<AccessResult>;
    searchProducts(term: string): Promise<Array<Product>>;
    searchServices(term: string): Promise<Array<Service>>;
    setUserActive(userId: Principal, active: boolean): Promise<void>;
    setUserRole(userId: Principal, role: Role): Promise<void>;
    updateCustomer(id: CustomerId, input: CustomerInput): Promise<Customer | null>;
    updateProduct(id: ProductId, input: ProductInput): Promise<Product | null>;
}
import type { AccessResult as _AccessResult, AccessStatus as _AccessStatus, ApprovedUser as _ApprovedUser, Branch as _Branch, Customer as _Customer, CustomerId as _CustomerId, CustomerInput as _CustomerInput, DocumentFilter as _DocumentFilter, DocumentId as _DocumentId, DocumentStatus as _DocumentStatus, DocumentType as _DocumentType, InventoryLocation as _InventoryLocation, LowStockItem as _LowStockItem, Product as _Product, ProductId as _ProductId, Role as _Role, SalesDocument as _SalesDocument, SalesDocumentInput as _SalesDocumentInput, SalesDocumentView as _SalesDocumentView, SalesItem as _SalesItem, SalesItemInput as _SalesItemInput, Service as _Service, StockAdjustmentReason as _StockAdjustmentReason, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async activateUser(arg0: Principal): Promise<AccessResult> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUser(arg0);
                return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUser(arg0);
            return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStock(arg0: ProductId, arg1: Branch, arg2: string, arg3: bigint, arg4: StockAdjustmentReason, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStock(arg0, to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_StockAdjustmentReason_n5(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStock(arg0, to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_StockAdjustmentReason_n5(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async approveUser(arg0: Principal, arg1: string, arg2: Role, arg3: Branch): Promise<AccessResult> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0, arg1, to_candid_Role_n7(this._uploadFile, this._downloadFile, arg2), to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0, arg1, to_candid_Role_n7(this._uploadFile, this._downloadFile, arg2), to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelDocument(arg0: DocumentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelDocument(arg0);
            return result;
        }
    }
    async confirmDocument(arg0: DocumentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmDocument(arg0);
            return result;
        }
    }
    async convertProformaToInvoice(arg0: DocumentId): Promise<SalesDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.convertProformaToInvoice(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertProformaToInvoice(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCustomer(arg0: CustomerInput): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(to_candid_CustomerInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Customer_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(to_candid_CustomerInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Customer_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createInvoice(arg0: SalesDocumentInput): Promise<SalesDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_SalesDocumentInput_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SalesDocument_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_SalesDocumentInput_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SalesDocument_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async createProforma(arg0: SalesDocumentInput): Promise<SalesDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.createProforma(to_candid_SalesDocumentInput_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SalesDocument_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProforma(to_candid_SalesDocumentInput_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SalesDocument_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createService(arg0: ServiceInput): Promise<Service> {
        if (this.processError) {
            try {
                const result = await this.actor.createService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createService(arg0);
            return result;
        }
    }
    async deactivateUser(arg0: Principal): Promise<AccessResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: DocumentId): Promise<SalesDocumentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockItems(): Promise<Array<LowStockItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getService(arg0: ServiceId): Promise<Service | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getService(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getService(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isInitialized(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInitialized();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInitialized();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApprovedUsers(): Promise<Array<ApprovedUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovedUsers();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovedUsers();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listCustomers(arg0: string | null): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCustomers(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCustomers(to_candid_opt_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDocuments(arg0: DocumentFilter): Promise<Array<SalesDocumentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDocuments(to_candid_DocumentFilter_n54(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDocuments(to_candid_DocumentFilter_n54(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLocationsByBranch(arg0: Branch): Promise<Array<InventoryLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLocationsByBranch(to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLocationsByBranch(to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listLocationsByProduct(arg0: ProductId): Promise<Array<InventoryLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLocationsByProduct(arg0);
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLocationsByProduct(arg0);
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPendingUsers(): Promise<Array<PendingUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPendingUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPendingUsers();
            return result;
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return result;
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return result;
        }
    }
    async rejectUser(arg0: Principal): Promise<AccessResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectUser(arg0);
                return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectUser(arg0);
            return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeStock(arg0: ProductId, arg1: Branch, arg2: bigint, arg3: StockAdjustmentReason, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStock(arg0, to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_StockAdjustmentReason_n5(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStock(arg0, to_candid_Branch_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_StockAdjustmentReason_n5(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async requestAccess(): Promise<AccessResult> {
        if (this.processError) {
            try {
                const result = await this.actor.requestAccess();
                return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestAccess();
            return from_candid_AccessResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return result;
        }
    }
    async searchServices(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchServices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchServices(arg0);
            return result;
        }
    }
    async setUserActive(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserActive(arg0, arg1);
            return result;
        }
    }
    async setUserRole(arg0: Principal, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: CustomerInput): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, to_candid_CustomerInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, to_candid_CustomerInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccessResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessResult): AccessResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AccessStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessStatus): AccessStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovedUser_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovedUser): ApprovedUser {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Branch_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Branch): Branch {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentStatus): DocumentStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryLocation_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryLocation): InventoryLocation {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_LowStockItem_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LowStockItem): LowStockItem {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_SalesDocumentView_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesDocumentView): SalesDocumentView {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_SalesDocument_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SalesDocument): SalesDocument {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesDocument]): SalesDocument | null {
    return value.length === 0 ? null : from_candid_SalesDocument_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentId]): DocumentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SalesDocumentView]): SalesDocumentView | null {
    return value.length === 0 ? null : from_candid_SalesDocumentView_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Service]): Service | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    status: _DocumentStatus;
    convertedToInvoiceId: [] | [_DocumentId];
    total: number;
    taxPercent: number;
    createdAt: _Timestamp;
    createdBy: _UserId;
    customerId: _CustomerId;
    items: Array<_SalesItem>;
    taxAmount: number;
    docType: _DocumentType;
    subtotal: number;
    documentNumber: string;
}): {
    id: DocumentId;
    status: DocumentStatus;
    convertedToInvoiceId?: DocumentId;
    total: number;
    taxPercent: number;
    createdAt: Timestamp;
    createdBy: UserId;
    customerId: CustomerId;
    items: Array<SalesItem>;
    taxAmount: number;
    docType: DocumentType;
    subtotal: number;
    documentNumber: string;
} {
    return {
        id: value.id,
        status: from_candid_DocumentStatus_n14(_uploadFile, _downloadFile, value.status),
        convertedToInvoiceId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.convertedToInvoiceId)),
        total: value.total,
        taxPercent: value.taxPercent,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        customerId: value.customerId,
        items: value.items,
        taxAmount: value.taxAmount,
        docType: from_candid_DocumentType_n17(_uploadFile, _downloadFile, value.docType),
        subtotal: value.subtotal,
        documentNumber: value.documentNumber
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CustomerId;
    taxId: [] | [string];
    name: string;
    email: [] | [string];
    phone: [] | [string];
}): {
    id: CustomerId;
    taxId?: string;
    name: string;
    email?: string;
    phone?: string;
} {
    return {
        id: value.id,
        taxId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.taxId)),
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.email)),
        phone: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    branch: _Branch;
    active: boolean;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
}): {
    principal: UserId;
    branch: Branch;
    active: boolean;
    name: string;
    createdAt: Timestamp;
    role: Role;
} {
    return {
        principal: value.principal,
        branch: from_candid_Branch_n31(_uploadFile, _downloadFile, value.branch),
        active: value.active,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n33(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    customerName: string;
    status: _DocumentStatus;
    convertedToInvoiceId: [] | [_DocumentId];
    total: number;
    taxPercent: number;
    createdAt: _Timestamp;
    createdBy: _UserId;
    customerId: _CustomerId;
    items: Array<_SalesItem>;
    taxAmount: number;
    docType: _DocumentType;
    subtotal: number;
    documentNumber: string;
}): {
    id: DocumentId;
    customerName: string;
    status: DocumentStatus;
    convertedToInvoiceId?: DocumentId;
    total: number;
    taxPercent: number;
    createdAt: Timestamp;
    createdBy: UserId;
    customerId: CustomerId;
    items: Array<SalesItem>;
    taxAmount: number;
    docType: DocumentType;
    subtotal: number;
    documentNumber: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_DocumentStatus_n14(_uploadFile, _downloadFile, value.status),
        convertedToInvoiceId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.convertedToInvoiceId)),
        total: value.total,
        taxPercent: value.taxPercent,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        customerId: value.customerId,
        items: value.items,
        taxAmount: value.taxAmount,
        docType: from_candid_DocumentType_n17(_uploadFile, _downloadFile, value.docType),
        subtotal: value.subtotal,
        documentNumber: value.documentNumber
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: _Branch;
    partNumber: string;
    name: string;
    minStockAlert: bigint;
    productId: _ProductId;
    quantity: bigint;
}): {
    branch: Branch;
    partNumber: string;
    name: string;
    minStockAlert: bigint;
    productId: ProductId;
    quantity: bigint;
} {
    return {
        branch: from_candid_Branch_n31(_uploadFile, _downloadFile, value.branch),
        partNumber: value.partNumber,
        name: value.name,
        minStockAlert: value.minStockAlert,
        productId: value.productId,
        quantity: value.quantity
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AccessStatus;
    principal: _UserId;
    branch: _Branch;
    approvedAt: _Timestamp;
    name: string;
    role: _Role;
}): {
    status: AccessStatus;
    principal: UserId;
    branch: Branch;
    approvedAt: Timestamp;
    name: string;
    role: Role;
} {
    return {
        status: from_candid_AccessStatus_n50(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        branch: from_candid_Branch_n31(_uploadFile, _downloadFile, value.branch),
        approvedAt: value.approvedAt,
        name: value.name,
        role: from_candid_Role_n33(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: _Branch;
    productId: _ProductId;
    updatedAt: _Timestamp;
    quantity: bigint;
    locationLabel: string;
}): {
    branch: Branch;
    productId: ProductId;
    updatedAt: Timestamp;
    quantity: bigint;
    locationLabel: string;
} {
    return {
        branch: from_candid_Branch_n31(_uploadFile, _downloadFile, value.branch),
        productId: value.productId,
        updatedAt: value.updatedAt,
        quantity: value.quantity,
        locationLabel: value.locationLabel
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Confirmed: null;
} | {
    Draft: null;
} | {
    Converted: null;
} | {
    Cancelled: null;
}): DocumentStatus {
    return "Confirmed" in value ? DocumentStatus.Confirmed : "Draft" in value ? DocumentStatus.Draft : "Converted" in value ? DocumentStatus.Converted : "Cancelled" in value ? DocumentStatus.Cancelled : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Invoice: null;
} | {
    Proforma: null;
}): DocumentType {
    return "Invoice" in value ? DocumentType.Invoice : "Proforma" in value ? DocumentType.Proforma : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    AlreadyApproved: null;
} | {
    AlreadyPending: null;
} | {
    NotFound: null;
} | {
    NotAuthorized: null;
} | {
    Requested: null;
}): AccessResult {
    return "ok" in value ? AccessResult.ok : "AlreadyApproved" in value ? AccessResult.AlreadyApproved : "AlreadyPending" in value ? AccessResult.AlreadyPending : "NotFound" in value ? AccessResult.NotFound : "NotAuthorized" in value ? AccessResult.NotAuthorized : "Requested" in value ? AccessResult.Requested : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Puyo: null;
} | {
    El_Topo: null;
}): Branch {
    return "Puyo" in value ? Branch.Puyo : "El_Topo" in value ? Branch.El_Topo : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Technician: null;
} | {
    Admin: null;
} | {
    Vendor: null;
}): Role {
    return "Technician" in value ? Role.Technician : "Admin" in value ? Role.Admin : "Vendor" in value ? Role.Vendor : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
}): AccessStatus {
    return "Inactive" in value ? AccessStatus.Inactive : "Active" in value ? AccessStatus.Active : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LowStockItem>): Array<LowStockItem> {
    return value.map((x)=>from_candid_LowStockItem_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApprovedUser>): Array<ApprovedUser> {
    return value.map((x)=>from_candid_ApprovedUser_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SalesDocumentView>): Array<SalesDocumentView> {
    return value.map((x)=>from_candid_SalesDocumentView_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryLocation>): Array<InventoryLocation> {
    return value.map((x)=>from_candid_InventoryLocation_n60(_uploadFile, _downloadFile, x));
}
function to_candid_Branch_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branch): _Branch {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CustomerInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomerInput): _CustomerInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentFilter_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentFilter): _DocumentFilter {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): _DocumentStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_DocumentType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SalesDocumentInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SalesDocumentInput): _SalesDocumentInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_StockAdjustmentReason_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockAdjustmentReason): _StockAdjustmentReason {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxId?: string;
    name: string;
    email?: string;
    phone?: string;
}): {
    taxId: [] | [string];
    name: string;
    email: [] | [string];
    phone: [] | [string];
} {
    return {
        taxId: value.taxId ? candid_some(value.taxId) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxPercent: number;
    customerId: CustomerId;
    items: Array<SalesItemInput>;
    docType: DocumentType;
}): {
    taxPercent: number;
    customerId: _CustomerId;
    items: Array<_SalesItemInput>;
    docType: _DocumentType;
} {
    return {
        taxPercent: value.taxPercent,
        customerId: value.customerId,
        items: value.items,
        docType: to_candid_DocumentType_n26(_uploadFile, _downloadFile, value.docType)
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: DocumentStatus;
    toDate?: Timestamp;
    fromDate?: Timestamp;
    customerId?: CustomerId;
    docType?: DocumentType;
}): {
    status: [] | [_DocumentStatus];
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
    customerId: [] | [_CustomerId];
    docType: [] | [_DocumentType];
} {
    return {
        status: value.status ? candid_some(to_candid_DocumentStatus_n56(_uploadFile, _downloadFile, value.status)) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        docType: value.docType ? candid_some(to_candid_DocumentType_n26(_uploadFile, _downloadFile, value.docType)) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    Invoice: null;
} | {
    Proforma: null;
} {
    return value == DocumentType.Invoice ? {
        Invoice: null
    } : value == DocumentType.Proforma ? {
        Proforma: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branch): {
    Puyo: null;
} | {
    El_Topo: null;
} {
    return value == Branch.Puyo ? {
        Puyo: null
    } : value == Branch.El_Topo ? {
        El_Topo: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentStatus): {
    Confirmed: null;
} | {
    Draft: null;
} | {
    Converted: null;
} | {
    Cancelled: null;
} {
    return value == DocumentStatus.Confirmed ? {
        Confirmed: null
    } : value == DocumentStatus.Draft ? {
        Draft: null
    } : value == DocumentStatus.Converted ? {
        Converted: null
    } : value == DocumentStatus.Cancelled ? {
        Cancelled: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StockAdjustmentReason): {
    Loss: null;
} | {
    Sale: null;
} | {
    Return: null;
} | {
    ServiceUse: null;
} | {
    Correction: null;
} | {
    Purchase: null;
} {
    return value == StockAdjustmentReason.Loss ? {
        Loss: null
    } : value == StockAdjustmentReason.Sale ? {
        Sale: null
    } : value == StockAdjustmentReason.Return ? {
        Return: null
    } : value == StockAdjustmentReason.ServiceUse ? {
        ServiceUse: null
    } : value == StockAdjustmentReason.Correction ? {
        Correction: null
    } : value == StockAdjustmentReason.Purchase ? {
        Purchase: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Technician: null;
} | {
    Admin: null;
} | {
    Vendor: null;
} {
    return value == Role.Technician ? {
        Technician: null
    } : value == Role.Admin ? {
        Admin: null
    } : value == Role.Vendor ? {
        Vendor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
